

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rentcar.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RentcarEntities : DbContext
{
    public RentcarEntities()
        : base("name=RentcarEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tipovehiculos> tipovehiculos { get; set; }

    public virtual DbSet<marcas> marcas { get; set; }

    public virtual DbSet<combustibles> combustibles { get; set; }

    public virtual DbSet<modelos> modelos { get; set; }

    public virtual DbSet<clientes> clientes { get; set; }

    public virtual DbSet<vehiculos> vehiculos { get; set; }

    public virtual DbSet<empleados> empleados { get; set; }

    public virtual DbSet<roles> roles { get; set; }

    public virtual DbSet<rentas> rentas { get; set; }

    public virtual DbSet<inspeccions> inspeccions { get; set; }

}

}

