//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rentcar.Models
{

using System;
    using System.Collections.Generic;
    
public partial class empleados
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public empleados()
    {

        this.rentas = new HashSet<rentas>();

        this.inspeccions = new HashSet<inspeccions>();

    }


    public int id { get; set; }

    public string full_name { get; set; }

    public string email { get; set; }

    public string cedula { get; set; }

    public string tanda { get; set; }

    public string comision { get; set; }

    public Nullable<System.DateTime> fecha_ingreso { get; set; }

    public string pass { get; set; }

    public Nullable<int> role_id { get; set; }

    public bool estado { get; set; }



    public virtual roles roles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<rentas> rentas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<inspeccions> inspeccions { get; set; }

}

}
