
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Rentcar.Models
{

using System;
    using System.Collections.Generic;
    
public partial class inspeccions
{

    public int id { get; set; }

    public Nullable<bool> ralladura { get; set; }

    public string combustible { get; set; }

    public Nullable<bool> goma_repuesto { get; set; }

    public Nullable<bool> gato { get; set; }

    public Nullable<bool> rotura_cristal { get; set; }

    public Nullable<bool> goma_superior_izquierda { get; set; }

    public Nullable<bool> goma_superior_derecha { get; set; }

    public Nullable<bool> goma_inferior_izquierda { get; set; }

    public Nullable<bool> goma_inferior_derecha { get; set; }

    public Nullable<System.DateTime> fecha_inspeccion { get; set; }

    public Nullable<int> empleado_id { get; set; }

    public Nullable<int> renta_id { get; set; }

    public Nullable<bool> estado { get; set; }



    public virtual empleados empleados { get; set; }

    public virtual rentas rentas { get; set; }

}

}
